### ISSUE TITLE
Second Impact and 3rd Strike music extracted to strange folders

### ISSUE THREAD

**Issue by petmac** [WydD/sf30ac-extractor#1]
Thank you for this utility.

After extracting, I found the Second Impact music was in the 3rd Strike folder, and the 3rd Strike music was in the Main folder.

A couple of caveats:
* I'm on a Mac and changed `\\` to `/` in `extract.py` to get the script running.
* Maybe this is an issue with how the game assets are bundled, not a bug in the extractor.

**Comment by WydD** [comment]
It's an issue with how the game assets are bundled 👍 And yeah the script was meant to be for windows and coded in less than an hour so i never tested this elsewhere :)
