### ISSUE TITLE
Use extractor on other games?  

### ISSUE THREAD

**Issue by rophel** [WydD/sf30ac-extractor#5]
Trying to use this on the SNK 40th Anniversary Collection.  It also has .mbundle files and a .plist.  

Extractor isn't working, any ideas?  Says files not found.

**Comment by Aurion81** [comment]
> Trying to use this on the SNK 40th Anniversary Collection. It also has .mbundle files and a .plist.
> 
> Extractor isn't working, any ideas? Says files not found.

This is exactly what I am trying to find out. If there is any hope of using something like this on the SNK 40th Anniversary Collection. If someone would make one, I would be very grateful!

**Comment by ghoost82** [comment]
I just create a pull request containing support for the SNK 40th Anniversary Collection. Until it is merged you could find my branch [here](https://github.com/ghoost82/sf30ac-extractor/tree/snk40th)

**Comment by WydD** [comment]
Well thanks for that and I actually discovered that python actually supported loads/dumps on bplist? Have you tried loading the SF30 manifest with plistlib in binary mode? If so we can just remove this part...

**Comment by ghoost82** [comment]
yes I have tried it and it failed, I think the binary format used is not compliant to the standard.

**Comment by WydD** [comment]
Merged
